import type { ThoughtFlowNode, GeminiChatMessage } from '../types/graph';

/**
 * Traverses upwards through parent references to get the strict branch history leading to targetNodeId.
 * Isolated from any parallel branches.
 */
export function getBranchAncestors(
  targetNodeId: string,
  nodesMap: Map<string, ThoughtFlowNode>
): ThoughtFlowNode[] {
  const visited = new Set<string>();
  const path: ThoughtFlowNode[] = [];

  function traverse(currentId: string) {
    if (visited.has(currentId)) return;
    visited.add(currentId);

    const node = nodesMap.get(currentId);
    if (!node) return;

    if (node.data.parentIds && node.data.parentIds.length > 0) {
      for (const parentId of node.data.parentIds) {
        traverse(parentId);
      }
    }

    path.push(node);
  }

  traverse(targetNodeId);

  return path.sort((a, b) => a.data.createdAt - b.data.createdAt);
}

/**
 * Converts a branch ancestor chain into standard Gemini API messages.
 * Ensures alternating 'user' and 'model' turns as required by Google Gemini.
 */
export function resolveGeminiContext(
  targetNodeId: string,
  nodes: ThoughtFlowNode[]
): GeminiChatMessage[] {
  const nodesMap = new Map(nodes.map((n) => [n.id, n]));
  const branchNodes = getBranchAncestors(targetNodeId, nodesMap);

  const messages: GeminiChatMessage[] = [];

  for (const node of branchNodes) {
    const role: 'user' | 'model' = node.data.role === 'assistant' ? 'model' : 'user';
    const text = node.data.content.trim();

    if (!text) continue;

    if (messages.length > 0 && messages[messages.length - 1].role === role) {
      messages[messages.length - 1].parts[0].text += `\n\n${text}`;
    } else {
      messages.push({
        role,
        parts: [{ text }],
      });
    }
  }

  if (messages.length > 0 && messages[0].role === 'model') {
    messages.unshift({
      role: 'user',
      parts: [{ text: '[Starting thought context]' }],
    });
  }

  return messages;
}

/**
 * Builds a multi-branch synthesis prompt when merging multiple paths.
 */
export function buildMergeSynthesisPrompt(
  selectedNodes: ThoughtFlowNode[],
  nodesMap: Map<string, ThoughtFlowNode>,
  userInstruction?: string
): { messages: GeminiChatMessage[]; promptText: string } {
  let branchSummaries = '';

  selectedNodes.forEach((node, index) => {
    const ancestors = getBranchAncestors(node.id, nodesMap);
    const branchLabel = node.data.branchLabel || `Branch ${index + 1}`;
    const role = node.data.role === 'assistant' ? 'Gemini Response' : 'User Idea';
    const modelTag = node.data.modelUsed ? ` [Generated by: ${node.data.modelUsed}]` : '';

    branchSummaries += `### ${branchLabel} (${role}${modelTag})\n`;
    branchSummaries += `**Key Point / Conclusion:**\n${node.data.content.trim()}\n\n`;

    if (ancestors.length > 1) {
      const priorStep = ancestors[ancestors.length - 2];
      branchSummaries += `*Preceding context:* "${priorStep.data.content.slice(0, 140)}..."\n\n`;
    }
    branchSummaries += `---\n\n`;
  });

  const promptText = `I am synthesizing conclusions from ${selectedNodes.length} different thought branches in my ideation canvas:

${branchSummaries}
**User Synthesis Goal:**
${userInstruction && userInstruction.trim().length > 0
  ? userInstruction.trim()
  : 'Synthesize the perspectives, reconcile trade-offs, and produce a unified, comprehensive conclusion with actionable next steps.'
}

Please provide:
1. **Executive Synthesis**: A unified perspective integrating the best ideas from all branches.
2. **Comparative Trade-offs**: How the branches complement or contrast with each other.
3. **Actionable Resolution**: Concrete next steps moving forward.`;

  return {
    messages: [
      {
        role: 'user',
        parts: [{ text: promptText }],
      },
    ],
    promptText,
  };
}

/**
 * Finds all leaf nodes (nodes with no children) in the graph.
 */
export function getLeafNodes(nodes: ThoughtFlowNode[], edges: { source: string; target: string }[]): ThoughtFlowNode[] {
  const parentIds = new Set(edges.map((e) => e.source));
  return nodes.filter((node) => !parentIds.has(node.id));
}
